name: Deploy to AWS testing
on:
  workflow_run:
    workflows:
      - Deploy to testing
    types:
      - requested
  push:
    branches:
      - aws-brazil-deploy

jobs:

  build-deploy:
    name: Build and deploy to AWS testing
    runs-on: ubuntu-latest
    environment:
      name: testing
      url: https://aws-testing.dark-worlds.lambdaclass.com/board

    steps:

    - name: Checkout deploy script
      uses: Bhacaz/checkout-files@v2
      with:
       files: server/deploy.sh

    - name: Create ssh private key file from env var
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        set -ex
        sed -E 's/(-+(BEGIN|END) OPENSSH PRIVATE KEY-+) *| +/\1\n/g' <<< "$SSH_KEY" > id_ed25519_testing
        chmod 400 id_ed25519_testing

    - name: Copy deploy script to server
      env:
        SSH_HOST: ${{ secrets.SSH_HOST_AWS }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME_AWS }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        SCRIPT_SRC: "server/deploy.sh"
        SCRIPT_DEST: "/root/deploy-script/"
      run: |
        set -ex
        scp -o StrictHostKeyChecking=no \
            -i id_ed25519_testing \
            -P ${SSH_PORT} \
            ${SCRIPT_SRC} \
            ${SSH_USERNAME}@${SSH_HOST}:${SCRIPT_DEST}
        ssh -i id_ed25519_testing \
            ${SSH_USERNAME}@${SSH_HOST} \
            chmod +x /root/deploy-script/deploy.sh

    - name: Execute deploy script
      env:
        SSH_HOST: ${{ secrets.SSH_HOST_AWS }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME_AWS }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        MIX_ENV: ${{ vars.MIX_ENV }}
        PHX_SERVER: ${{ vars.PHX_SERVER }}
        PHX_HOST: ${{ vars.PHX_HOST_AWS }}
        SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NEWRELIC_APP_NAME: ${{ vars.NEWRELIC_APP_NAME_AWS }}
        NEWRELIC_KEY: ${{ secrets.NEWRELIC_KEY }}
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      run: |
        set -ex
        ssh -o StrictHostKeyChecking=no \
            -i id_ed25519_testing \
            -p ${SSH_PORT} \
            ${SSH_USERNAME}@${SSH_HOST} \
              BRANCH_NAME=${BRANCH_NAME} \
              MIX_ENV=${MIX_ENV} \
              PHX_SERVER=${PHX_SERVER} \
              PHX_HOST=${PHX_HOST} \
              SECRET_KEY_BASE=${SECRET_KEY_BASE} \
              DATABASE_URL=${DATABASE_URL} \
              NEWRELIC_APP_NAME=${NEWRELIC_APP_NAME} \
              NEWRELIC_KEY=${NEWRELIC_KEY} \
              /root/deploy-script/deploy.sh
